### ISSUE TITLE
Is it possible to override the registry

### ISSUE THREAD

**Issue by TomPradat** [npm/npx#28]
# What / Why

It would be great to be able to override the registry as we can do with `npm install`.

For example : `npx create-react-app --registry https://registry.npmjs.org`

This is useful for instance if you use a private registry and it's down for some reason. The only work around is to set the npm config and unset it later.

**Comment by ljharb** [comment]
`NPM_CONFIG_REGISTRY=https://registry.npmjs.org npx create-react-app`?

**Comment by TomPradat** [comment]
Yeap, I missed this one, thanks :+1:
