### ISSUE TITLE
GHSL-2020-121

### ISSUE THREAD

**Issue by kevinbackhouse** [npm/npx#60]
Hello,

I am a member of the GitHub Security Lab (https://securitylab.github.com).

I've attempted to reach a maintainer for this project to report a potential security issue but have been unable to verify the report was received. Please could a project maintainer could contact us at securitylab@github.com, using reference GHSL-2020-121?

Thank you,
Kevin Backhouse
GitHub Security Lab

**Comment by darcyclarke** [comment]
@kevinbackhouse I know we just sync'd up internally; Definitely let me know if there's anything to follow up with here - Otherwise, it would be good to close this for visibility/comms. Definitely feel free to ping me if there's any issues filing against that other repo mentioned. Thanks! 😄
