### ISSUE TITLE
[BUG] Window Username contain a space...

### ISSUE THREAD

**Issue by mrnossiom** [npm/npx#75]
### Current Behavior
* I've got this error: 
```
npm ERR! code ENOLOCAL
npm ERR! Could not install from "Invitée\AppData\Roaming\npm-cache\_npx\12672" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Famille Invitée\AppData\Roaming\npm-cache\_logs\2020-08-13T16_44_08_162Z-debug.log
Install for [ 'lolcatjs@latest' ] failed with code 1
```

### Steps to Reproduce
* Use a windows name with spaces in it
* Try `echo hello | npx lolcatjs`

### Expected Behavior
* Normaly I have to get a beautiful rainbow hello
* The path is trimed at the space because normaly this path:
`"Invitée\AppData\Roaming\npm-cache\_npx\12672"` 
* must be this path (or something like this...):
`"C:\Users\Famille Invitée\AppData\Roaming\npm-cache\_npx\12672"`

My npx version (latest I think): `6.14.6`
It must be a problem of parsing the path....

**Comment by mrnossiom** [comment]
This is also to reopen the issue #6

**Comment by bnb** [comment]
Just witnessed someone hit this as well.

**Comment by mrnossiom** [comment]
Think that has been fixed with the new version...
