### ISSUE TITLE
[FEATURE] change npx to be an aliase of npm exec or move code of npm exec in npx

### ISSUE THREAD

**Issue by mrnossiom** [npm/npx#83]
Everithing is in the title:
change npx to be an aliase of npm exec or move code of npm exec in npx

Thanks

**Comment by ljharb** [comment]
Both have already happened. `npx` in npm 7+ is just an alias for `npm exec`, and the code in this repo is no longer depended upon by npm itself.

**Comment by mrnossiom** [comment]
Ah ok
