### ISSUE TITLE
[BUG] NPX uses cached GIST instead of latest

### ISSUE THREAD

**Issue by asears** [npm/npx#96]
# What / Why

Installing from Gist using package.json and js file is a really interesting use of npx.  

Trying this out on Windows, I found it cached the first gist version of the package and any changes to the gist weren't picked up.  

Deleting the cache fixes this.  Is there a command line option to delete the cache?

## When

Running npx 7.5.1.  I was able to replicate by simply creating a basic gist with an error, then trying to fix it.

https://gist.github.com/asears/cf8d95776e13f6472c1fb56b57659400

## Where
Command line on Windows.

### Current Behavior

* n/a

### Steps to Reproduce

1. Create a gist with a bug.
2. npx https://my-gist-url
3. Fix the gist
4. npx https://my-gist-url

Cached version will be used.

### Expected Behavior

Should install latest Gist.

## Who

* n/a

## References

* n/a

**Comment by ljharb** [comment]
npx in npm 7 lives inside the cli repo; I’d suggest filing this there.

**Comment by ljharb** [comment]
moved to https://github.com/npm/cli/issues/2641
